[platformio]
src_dir = .
include_dir = .

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
lib_deps =
    bblanchon/ArduinoJson@^7
build_flags =
    -DBOARD_HAS_PSRAM
